services:
  mysql:
    image: mysql:8.0
    container_name: pujcovna-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pujcovna
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: